add_newline = false

[character]
success_symbol = "[->](bold green) "
error_symbol = "[->](bold red) "

[package]
disabled = false

[hostname]
ssh_only = false
style = "bold green"

[username]
show_always = true
format = "[$user]($style)@"
